/* ── Critical & Social Theory (7) + Community of Inquiry + Identity Formation ── */
,
 {
  id:"crt", name:"Critical Race Theory", discipline:"Critical &amp; Social Theory", depth:"starter",
  theorists:"Derrick Bell, Kimberlé Crenshaw, Richard Delgado, Mari Matsuda (legal studies, 1970s–80s); brought into education by Gloria Ladson-Billings &amp; William Tate (1995)",
  tagline:"A legal-studies framework holding that race is socially constructed and that racial inequality persists through ordinary institutional arrangements, not only through individual prejudice.",
  claims:["Race is a social construction with material consequences, not a biological fact.","Racism is understood as ordinary and embedded in routine institutional operation rather than exceptional and individual.","Interest convergence: advances for minoritized groups tend to occur when they also serve majority interests (Bell).","Intersectionality: systems of disadvantage compound and cannot be analyzed one axis at a time (Crenshaw).","Counter-storytelling treats the experiential knowledge of people of color as legitimate evidence.","A critique of liberalism: colorblindness and incrementalism are argued to preserve existing arrangements."],
  constructs:[{term:"Interest convergence", def:"Bell's thesis that racial progress occurs when it aligns with majority interests."},{term:"Intersectionality", def:"Crenshaw's analysis of how race, gender and class operate together rather than separately."},{term:"Counter-storytelling", def:"Narrative from marginalized standpoints used as an analytic method."},{term:"Whiteness as property", def:"Harris's argument that whiteness historically functioned as a legally protected asset."},{term:"Permanence of racism", def:"The working assumption that racism is endemic rather than aberrational."}],
  applications:["Education research on discipline disparities, tracking, gifted identification, and school funding.","Policy analysis that examines outcomes and mechanisms rather than stated intent.","Qualitative methodology — counter-narrative as a recognized form of evidence."],
  critiques:["Contested within the academy on methodology: critics argue narrative evidence resists falsification and that core claims are difficult to test empirically.","The permanence-of-racism premise is criticized as unfalsifiable by design.","Its critique of liberal proceduralism draws sustained objection from scholars who defend colorblind principles on moral grounds.","The term is used very differently in public political debate than in the scholarly literature — in a dissertation, define which sense you mean and cite primary sources.","In education it is often invoked loosely as a synonym for any equity work, which the originating scholars did not intend."],
  related:["freire","bourdieu","crp","funds","interactionism"],
  refs:["Bell, D. A. (1980). Brown v. Board of Education and the interest-convergence dilemma. <i>Harvard Law Review, 93</i>(3), 518–533.","Crenshaw, K. (1989). Demarginalizing the intersection of race and sex. <i>University of Chicago Legal Forum, 1989</i>(1), 139–167.","Ladson-Billings, G., &amp; Tate, W. F. (1995). Toward a critical race theory of education. <i>Teachers College Record, 97</i>(1), 47–68.","Delgado, R., &amp; Stefancic, J. (2017). <i>Critical race theory: An introduction</i> (3rd ed.). NYU Press."]
 },
 {
  id:"feminist", name:"Feminist Theory", discipline:"Critical &amp; Social Theory", depth:"starter",
  theorists:"Simone de Beauvoir (1949); bell hooks; Nancy Fraser; Sandra Harding (standpoint theory); Patricia Hill Collins",
  tagline:"A family of theories analyzing how gendered power is produced and maintained — and arguing that knowledge itself is positioned rather than neutral.",
  claims:["Gender is a structuring principle of social institutions, not a demographic variable to control for.","Standpoint theory: knowledge is situated, and the perspective of marginalized groups can reveal what dominant positions obscure.","Different strands prescribe differently — liberal feminism seeks equal access, radical and socialist strands target the structures themselves.","Black feminist thought (Collins) insists that race, class and gender be analyzed together rather than additively.","The researcher's own position shapes the research and should be declared, not hidden."],
  constructs:[{term:"Patriarchy", def:"Systematic organization of social life around male authority."},{term:"Standpoint theory", def:"Harding's argument that marginalized positions offer epistemic advantage on certain questions."},{term:"Strong objectivity", def:"Harding's claim that declaring position increases rather than reduces rigor."},{term:"Matrix of domination", def:"Collins's account of interlocking systems of oppression."},{term:"Positionality", def:"The researcher's social location as a methodological fact to be examined."}],
  applications:["Research on gendered patterns in leadership, participation, discipline and subject choice.","Methodological grounding for reflexive and positionality statements.","Analysis of curriculum and whose knowledge is represented in it."],
  critiques:["Not one theory but many, with real internal disagreement — naming 'feminist theory' as a framework without specifying the strand is a common dissertation weakness.","Standpoint theory faces the objection that it risks essentializing group experience.","Second-wave formulations were criticized by women of color for universalizing white middle-class experience; that critique produced intersectional approaches.","Normative commitments are explicit, which some reviewers treat as a limitation and advocates treat as honesty."],
  related:["crt","queer","gender_theory","bourdieu","practitioner"],
  refs:["de Beauvoir, S. (1949/2011). <i>The second sex</i> (C. Borde &amp; S. Malovany-Chevallier, Trans.). Vintage.","Harding, S. (1991). <i>Whose science? Whose knowledge?</i> Cornell University Press.","Collins, P. H. (2000). <i>Black feminist thought</i> (2nd ed.). Routledge.","hooks, b. (2000). <i>Feminism is for everybody.</i> South End Press."]
 },
 {
  id:"queer", name:"Queer Theory", discipline:"Critical &amp; Social Theory", depth:"starter",
  theorists:"Teresa de Lauretis (coined the term, 1990); Judith Butler (1990); Eve Kosofsky Sedgwick (1990); Michael Warner",
  tagline:"A critique of the idea that identity categories are stable or natural — including the categories the theory itself is named after.",
  claims:["Sexual and gender categories are historically produced rather than natural kinds.","Butler: gender is performative — constituted through repeated acts rather than expressing a prior inner essence.","Heteronormativity names the assumption of heterosexuality as default, built into institutions and curricula.","The project is anti-normative: it resists stabilizing any identity category, including queer itself.","Normalcy, not deviance, is the thing requiring explanation."],
  constructs:[{term:"Performativity", def:"Butler's claim that gender is produced by its repetition, not expressed by it."},{term:"Heteronormativity", def:"The institutional assumption of heterosexuality as unmarked default."},{term:"The closet", def:"Sedgwick's analysis of the knowledge structures organizing disclosure and silence."},{term:"Anti-normativity", def:"Refusal to replace one stable category with another."}],
  applications:["Analysis of curriculum, policy and school climate for assumptions about family, gender and the body.","Research on LGBTQ+ student experience that does not treat identity as a fixed variable.","Critique of how 'inclusion' programs can reinscribe the norms they intend to widen."],
  critiques:["Deliberate resistance to stable categories makes operationalization in empirical research genuinely difficult.","Prose style in foundational texts is notoriously dense, which limits uptake by practitioners.","Critics within queer studies argue anti-normativity has become its own orthodoxy.","Tension with identity-based political organizing, which requires the stable categories the theory destabilizes."],
  related:["feminist","gender_theory","crt","interactionism"],
  refs:["Butler, J. (1990). <i>Gender trouble: Feminism and the subversion of identity.</i> Routledge.","Sedgwick, E. K. (1990). <i>Epistemology of the closet.</i> University of California Press.","de Lauretis, T. (1991). Queer theory: Lesbian and gay sexualities. <i>differences, 3</i>(2), iii–xviii.","Warner, M. (1991). Introduction: Fear of a queer planet. <i>Social Text, 29</i>, 3–17."]
 },
 {
  id:"gender_theory", name:"Gender Theory", discipline:"Critical &amp; Social Theory", depth:"starter",
  theorists:"Candace West &amp; Don Zimmerman ('doing gender', 1987); Raewyn Connell (1995); Sandra Bem (gender schema, 1981)",
  tagline:"Gender as something accomplished in interaction and organized by institutions — distinct from sex, and distinct from the critique of identity categories in queer theory.",
  claims:["Gender is produced in ongoing social interaction — West and Zimmerman's 'doing gender' — and people are held accountable to it.","Connell: multiple masculinities and femininities exist in hierarchical relation; hegemonic masculinity is the culturally dominant pattern, not the most common one.","Gender operates at three levels simultaneously: individual identity, interaction, and institutional structure.","Bem's gender schema theory explains how children acquire the cognitive lens that organizes gendered information."],
  constructs:[{term:"Doing gender", def:"Gender as an ongoing accomplishment in interaction rather than a stable attribute."},{term:"Hegemonic masculinity", def:"Connell's term for the dominant and culturally authorized pattern of masculinity."},{term:"Gender schema", def:"Bem's cognitive structure organizing perception along gender lines."},{term:"Sex / gender distinction", def:"The analytic separation of biological categories from social organization — itself contested."}],
  applications:["Research on participation patterns in STEM, PE, CTE and leadership roles.","Analysis of discipline data and behavioral expectations by gender.","Understanding how boys' and girls' school experiences diverge without assuming innate cause."],
  critiques:["The sex/gender distinction is contested from several directions and should not be asserted as settled.","Overlaps substantially with feminist and queer theory; a dissertation naming 'gender theory' alone will be asked to be more specific.","'Hegemonic masculinity' is frequently used loosely as a synonym for bad male behavior, which Connell explicitly rejected.","Most empirical work is correlational and culturally specific."],
  related:["feminist","queer","interactionism","crt","erikson"],
  refs:["West, C., &amp; Zimmerman, D. H. (1987). Doing gender. <i>Gender &amp; Society, 1</i>(2), 125–151.","Connell, R. W. (1995). <i>Masculinities.</i> University of California Press.","Bem, S. L. (1981). Gender schema theory. <i>Psychological Review, 88</i>(4), 354–364.","Connell, R. W., &amp; Messerschmidt, J. W. (2005). Hegemonic masculinity: Rethinking the concept. <i>Gender &amp; Society, 19</i>(6), 829–859."]
 },
 {
  id:"marxist", name:"Marxist Theory &amp; Social Reproduction", discipline:"Critical &amp; Social Theory", depth:"starter",
  theorists:"Karl Marx; in education Samuel Bowles &amp; Herbert Gintis (1976); Michael Apple; Paul Willis (1977)",
  tagline:"Schooling analyzed as an institution that reproduces the class structure of the economy it serves, whatever its stated purposes.",
  claims:["Material conditions and relations of production shape consciousness and institutions, including schools.","Bowles and Gintis's correspondence principle: the social relations of schooling mirror those of the workplace students are destined for.","Ideology operates by making arrangements appear natural and inevitable rather than chosen.","Willis showed reproduction is not passive — working-class 'lads' actively resisted school and in doing so secured their own subordination.","Credentialism can expand without reducing inequality, because relative position is what the credential buys."],
  constructs:[{term:"Correspondence principle", def:"The structural match between school hierarchies and workplace hierarchies."},{term:"Hidden curriculum", def:"The norms and dispositions schools teach without naming — punctuality, deference, competition."},{term:"Ideology", def:"Beliefs that render a contingent social order natural."},{term:"Social reproduction", def:"The intergenerational transmission of class position through institutional means."},{term:"Resistance", def:"Willis's finding that opposition can reproduce subordination rather than escape it."}],
  applications:["Analysis of tracking, vocational pathways, school funding, and credential inflation.","Interrogating the hidden curriculum of a school's routines.","Policy critique that looks past stated intent to structural effect."],
  critiques:["Early versions were strongly deterministic and left little room for agency; Willis and Apple were responses to that.","Economic reductionism underweights race, gender and culture as independent structuring forces.","Empirically hard to test as a whole theory; most support is historical and interpretive.","The political history of Marxism as a governing ideology colors reception of the analytic tradition, and the two should be kept distinct in academic writing."],
  related:["bourdieu","freire","functionalist","crt","interactionism"],
  refs:["Bowles, S., &amp; Gintis, H. (1976). <i>Schooling in capitalist America.</i> Basic Books.","Willis, P. (1977). <i>Learning to labour.</i> Saxon House.","Apple, M. W. (2004). <i>Ideology and curriculum</i> (3rd ed.). RoutledgeFalmer.","Anyon, J. (1980). Social class and the hidden curriculum of work. <i>Journal of Education, 162</i>(1), 67–92."]
 },
 {
  id:"functionalist", name:"Functionalist Theory", discipline:"Critical &amp; Social Theory", depth:"starter",
  theorists:"Émile Durkheim (1893, 1922); Talcott Parsons (1959); Robert K. Merton (1949)",
  tagline:"Social institutions are explained by the functions they perform for the stability of the whole — the tradition most other social theories were written against.",
  claims:["Society is a system of interdependent parts, each contributing to overall stability.","Durkheim: education transmits shared values and produces the social solidarity a complex society requires.","Parsons: the school class is the mechanism that moves children from ascribed family status to achieved adult roles.","Merton distinguished manifest from latent functions — intended purposes from unintended but real ones.","Merton's dysfunction concept allowed the tradition to account for arrangements that harm the system."],
  constructs:[{term:"Social solidarity", def:"Durkheim's cohesion problem: what holds a differentiated society together."},{term:"Manifest vs latent function", def:"Stated purpose versus actual unacknowledged effect."},{term:"Dysfunction", def:"Merton's concession that some arrangements damage the system that sustains them."},{term:"Socialization and allocation", def:"Parsons's two functions of schooling — forming values and sorting people."},{term:"Meritocratic sorting", def:"The claim that schools allocate roles by achievement rather than birth."}],
  applications:["Historical analysis of why compulsory schooling took the shape it did.","A named counterposition in literature reviews — most critical theory is a reply to this one.","Examining the latent functions of a school practice alongside its stated purpose."],
  critiques:["Explains stability well and change poorly; conflict is treated as malfunction rather than as normal.","Tends toward justifying existing arrangements by showing they are functional.","The meritocratic sorting claim is directly contradicted by social reproduction research.","Teleological risk: assuming a practice exists because of the function it happens to serve."],
  related:["marxist","bourdieu","systems","interactionism"],
  refs:["Durkheim, É. (1922/1956). <i>Education and sociology.</i> Free Press.","Parsons, T. (1959). The school class as a social system. <i>Harvard Educational Review, 29</i>(4), 297–318.","Merton, R. K. (1949). <i>Social theory and social structure.</i> Free Press."]
 },
 {
  id:"intersubjectivity", name:"Intersubjectivity Theory", discipline:"Critical &amp; Social Theory", depth:"starter",
  theorists:"Edmund Husserl; Alfred Schutz (1932); Colwyn Trevarthen (developmental, 1979); Daniel Stern; Jessica Benjamin",
  tagline:"Shared understanding between minds is not a lucky outcome of communication — it is the precondition that makes communication possible at all.",
  claims:["Meaning is achieved between people rather than transmitted from one to another.","Trevarthen: infants show primary intersubjectivity from the first months — the capacity is foundational, not learned late.","Secondary intersubjectivity, around nine months, adds joint attention to a shared object; this is where teaching becomes possible.","Schutz: everyday social life runs on a reciprocity of perspectives we assume without checking.","Attunement — being accurately read by another — is itself developmentally consequential."],
  constructs:[{term:"Primary intersubjectivity", def:"Early dyadic attunement between infant and caregiver."},{term:"Secondary intersubjectivity", def:"Joint attention to a third object — the structure underlying all instruction."},{term:"Reciprocity of perspectives", def:"Schutz's taken-for-granted assumption that we would see the same thing in each other's place."},{term:"Attunement", def:"Accurate reading of another's state, and the experience of being so read."},{term:"Lifeworld", def:"The shared pre-reflective world within which understanding takes place."}],
  applications:["Phenomenological and relational research methodologies.","Analysis of teacher–student relationship quality beyond rapport or liking.","Grounding for coaching models that treat the relationship as the mechanism rather than the setting."],
  critiques:["Highly abstract and difficult to operationalize for empirical study.","Spans philosophy, developmental psychology and psychoanalysis with different meanings in each — specify which literature you are drawing on.","Developmental claims about infant capacity continue to be debated.","Frequently invoked in qualitative work as a gesture toward connection rather than as an analytic commitment."],
  related:["vygotsky","situated","interactionism","lead_relational","schon"],
  refs:["Schutz, A. (1932/1967). <i>The phenomenology of the social world.</i> Northwestern University Press.","Trevarthen, C. (1979). Communication and cooperation in early infancy. In M. Bullowa (Ed.), <i>Before speech.</i> Cambridge University Press.","Stern, D. N. (1985). <i>The interpersonal world of the infant.</i> Basic Books.","Benjamin, J. (1988). <i>The bonds of love.</i> Pantheon."]
 },
 {
  id:"comm_inquiry", name:"Community of Inquiry Framework", discipline:"Technology &amp; Digital Learning", depth:"starter",
  theorists:"D. Randy Garrison, Terry Anderson &amp; Walter Archer (2000)",
  tagline:"Deep learning online requires three overlapping presences — social, cognitive and teaching — and the framework exists because any one alone fails.",
  claims:["Social presence: participants project themselves as real people, which makes academic risk-taking possible.","Cognitive presence: meaning is constructed through a four-phase inquiry cycle — triggering event, exploration, integration, resolution.","Teaching presence: design, facilitation and direct instruction, which may be distributed among participants.","The educational experience sits at the intersection; remove any presence and the other two degrade.","Most online discussion stalls at exploration and never reaches integration or resolution."],
  constructs:[{term:"Social presence", def:"Projecting personal identity into a mediated environment."},{term:"Cognitive presence", def:"Sustained construction of meaning through the practical inquiry cycle."},{term:"Teaching presence", def:"Design, facilitation and direct instruction — the element most predictive of outcomes."},{term:"Practical inquiry cycle", def:"Triggering event → exploration → integration → resolution."},{term:"The integration bottleneck", def:"The empirically observed tendency of online discussion to stop before synthesis."}],
  applications:["Design and evaluation of online and hybrid courses, including doctoral programs.","Diagnosing why an online discussion board generates volume without depth.","A widely used framework for dissertations on virtual learning environments."],
  critiques:["Largely validated through self-report survey instruments and transcript coding, both with known limitations.","Cognitive presence is the hardest to measure and the least consistently evidenced of the three.","Developed for text-based asynchronous discussion; fit to video, synchronous and AI-mediated settings is unsettled.","Descriptive rather than causal — it maps what a good online course contains without establishing what produces it."],
  related:["situated","sense_community","connectivism","vygotsky","digital_writing"],
  refs:["Garrison, D. R., Anderson, T., &amp; Archer, W. (2000). Critical inquiry in a text-based environment. <i>The Internet and Higher Education, 2</i>(2–3), 87–105.","Garrison, D. R., &amp; Arbaugh, J. B. (2007). Researching the community of inquiry framework. <i>The Internet and Higher Education, 10</i>(3), 157–172.","Rourke, L., &amp; Kanuka, H. (2009). Learning in communities of inquiry: A review of the literature. <i>Journal of Distance Education, 23</i>(1), 19–48."]
 },
 {
  id:"identity_formation", name:"Identity Formation &amp; Identity Status", discipline:"Psychology", depth:"starter",
  theorists:"Erik Erikson (1968); operationalized by James Marcia (1966); extended by Jane Kroger and Koen Luyckx",
  tagline:"Adolescent identity is formed through two processes — exploring options and committing to some — which cross to produce four distinct statuses.",
  claims:["Identity formation turns on two dimensions: exploration of alternatives and commitment to choices.","Crossing them yields four statuses: diffusion (neither), foreclosure (commitment without exploration), moratorium (exploration without commitment), achievement (both).","Statuses are not a fixed ladder; people move among them, and movement can run backwards.","Moratorium is uncomfortable and developmentally productive — distress during it is not pathology.","Foreclosure looks like maturity from outside: settled, compliant, and untested."],
  constructs:[{term:"Exploration", def:"Active consideration of alternative roles, beliefs and commitments."},{term:"Commitment", def:"Investment in a chosen direction."},{term:"Identity diffusion", def:"Neither exploring nor committed."},{term:"Foreclosure", def:"Committed without having explored — usually to inherited expectations."},{term:"Moratorium", def:"Actively exploring, not yet committed."},{term:"Identity achievement", def:"Committed after genuine exploration."}],
  applications:["Advisory, counseling and college-and-career readiness work with adolescents.","Making sense of the student who abruptly abandons a long-held plan.","Doctoral-student development research, where moratorium is a common and under-named experience."],
  critiques:["Marcia's statuses operationalize a narrower slice of Erikson than his theory contains.","Originally validated on Western, largely male samples; cultural specificity of 'exploration' as a value is a real limitation.","Status is typically measured by interview or self-report at one time point, which suits a dynamic process poorly.","Often used descriptively as a labeling scheme rather than as an account of process."],
  related:["erikson","mezirow","practitioner","sdt","gender_theory"],
  refs:["Erikson, E. H. (1968). <i>Identity: Youth and crisis.</i> Norton.","Marcia, J. E. (1966). Development and validation of ego identity status. <i>Journal of Personality and Social Psychology, 3</i>(5), 551–558.","Kroger, J., &amp; Marcia, J. E. (2011). The identity statuses: Origins, meanings, and interpretations. In S. J. Schwartz et al. (Eds.), <i>Handbook of identity theory and research.</i> Springer."]
 }
