
/* School-subject clusters: the same theories, asked from the other direction —
   "I teach this subject; what applies to me?" Disciplines above are where a
   theory came from; these are where it gets used. */
const SUBJ=[
 {label:"🏃 PE & Health", q:"I teach PE or health.", why:"The only subject whose content is the body. Movement models and motivation theory carry most of the weight here — and the motivation research in PE is unusually strong, because PE is where students most visibly opt in or out.", ids:["mosston","sdt","achievementgoal","physlit","fitt","sported","tpsr","socialcognitive","ericsson","flow","cogload","implementation","mindset"]},
 {label:"📖 English & Language Arts", q:"I teach English or language arts.", why:"Reading and writing are the two most heavily theorized acts in schooling. Comprehension depends on knowledge as much as decoding, and writing is a thinking process before it is a product.", ids:["svr","chall","schema","rosenblatt","literary_crit","flowerhayes","writing_sociocultural","wtl","nls","digital_writing","toulmin","bruner_narrative","desirable"]},
 {label:"🔢 Mathematics", q:"I teach mathematics.", why:"The central problem is procedural fluency without understanding. Representation, worked structure, and misconception-aware teaching matter more here than almost anywhere else.", ids:["math_cra","math_rme","skemp","cogload","desirable","conceptualchange","pbl","discovery","transfer","multimedia","formative"]},
 {label:"🔬 Science", q:"I teach science.", why:"Students arrive with intuitive theories that instruction must confront rather than overwrite. Note the warning inside: unguided inquiry performs badly, and guided inquiry performs well.", ids:["conceptualchange","inquiry","pbl","discovery","dissonance","cogload","schema","toulmin","dbr","multimedia","transfer","desirable"]},
 {label:"🏛 Social Studies", q:"I teach social studies.", why:"The discipline's real content is how claims about the past and the social world get made and tested. Several of the social theories here are also the lenses the subject studies.", ids:["wineburg","toulmin","fallacies","bruner_narrative","freire","marxist","functionalist","bourdieu","crt","interactionism","dualprocess","nudge","prospect","epistemology"]},
 {label:"🎭 Fine Arts", q:"I teach music, visual art, or theatre.", why:"Arts learning has its own cognitive case — and the craft traditions of the studio were doing deliberate practice and critique long before either had a research literature.", ids:["eisner","gardner_mi","ericsson","flow","constructionism","hcd","situated","mosston","socialcognitive","desirable"]},
 {label:"🗣 World Languages", q:"I teach a world language.", why:"The general theories below apply well — interaction, scaffolding, spacing, literacy. Second-language acquisition theory specifically (Krashen, Swain, Long, ACTFL proficiency) is not yet in this Lab; it is the clearest gap.", ids:["vygotsky","situated","schema","desirable","cogload","socialcognitive","sdt","nls","transfer","interactionism"]},
 {label:"🔧 CTE & Electives", q:"I teach CTE, computer science, or an elective.", why:"Learning organized around real production and real audiences. The apprenticeship traditions fit these rooms better than the classroom traditions do.", ids:["situated","kolb","ericsson","constructionism","pbl","hcd","discovery","transfer","knowles","dewey","connectivism","socialcognitive"]},
 {label:"♿ Special Education & Intervention", q:"I teach special education or run interventions.", why:"Design for variability, manage load deliberately, and make the invisible explicit. Several entries here have the strongest evidence base in the Lab — and one of the most popular has the weakest.", ids:["udl","cogload","barkley","adhd_strategies","dualpathway_adhd","behaviorism","math_cra","svr","vygotsky","implementation","formative","desirable"]},
 {label:"🧑‍💼 Leadership & Administration", q:"I lead a school, a team, or an initiative.", why:"Six decades of leadership theory, each generation written against the last. Read them in order and the field's argument with itself becomes visible.", ids:["lead_transformational","lead_servant","lead_relational","lead_situational","lead_trait","lead_behavioral","systems","change_theory","sense_community","improvement","agency","schon","mezirow"]},
 {label:"🔎 Dissertation frameworks", q:"I need a theoretical framework for my study.", why:"The theories most often chosen to frame education dissertations — critical, social, developmental and organizational. A framework is a commitment about what counts as evidence, so choose it before the method, not after.", ids:["crt","feminist","queer","gender_theory","marxist","functionalist","intersubjectivity","identity_formation","comm_inquiry","systems","change_theory","bourdieu","freire","practitioner","dbr","epistemology"]},
 {label:"🌐 Every subject", q:"I want what works in any classroom.", why:"The theories that are not about a subject at all. If you only ever read one cluster in this Lab, read this one.", ids:["desirable","cogload","infoprocessing","schema","transfer","piaget","vygotsky","sdt","formative","mindset","attribution","expectancyvalue","srl","maslow","erikson","udl","crp","funds","backward","bloom","multimedia","socialcognitive"]}
];
